name: Dependency Check Scan

on:
  workflow_dispatch:

jobs:
  dependency-check:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Dependency-Check v12.1.0
        run: |
          Invoke-WebRequest -Uri https://github.com/jeremylong/DependencyCheck/releases/download/v12.1.0/dependency-check-12.1.0-release.zip -OutFile dc.zip
          Expand-Archive dc.zip -DestinationPath dc

      - name: Run Dependency-Check
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          ./dc/dependency-check/bin/dependency-check.bat `
            --project "MyProject" `
            --scan "." `
            --format "HTML" `
            --out "dependency-check-report" `
            --nvdApiKey "$env:NVD_API_KEY"

      - name: Upload report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report
