name: Dependency-Check Scan

on:
  workflow_dispatch: # run manually from the Actions tab

jobs:
  owasp-scan:
    runs-on: ubuntu-latest  # using GitHub-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Java (needed for Dependency-Check)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Download Dependency-Check
        run: |
          curl -L -o dependency-check.zip \
            https://github.com/jeremylong/DependencyCheck/releases/latest/download/dependency-check.zip
          unzip dependency-check.zip -d dependency-check

      - name: Run Dependency-Check
        run: |
          ./dependency-check/dependency-check/bin/dependency-check.sh \
            --scan . \
            --format HTML \
            --out reports \
            --nvdApiKey ${{ secrets.NVD_API_KEY }}
            --noupdate

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports
